name: Project Invisible Guardrails
on: [push, pull_request]

jobs:
  # LANE 1: FAST CHECKS (CPU)
  code-quality:
    runs-on: linux_gpu
    steps:
      - uses: actions/checkout@v3
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check invisible_core/ --ignore E501

  # LANE 2: ADVERSARIAL TEST (GPU)
  # Only runs on 'dev' or 'main' branches
  adversarial-benchmark:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    runs-on: linux_gpu
    container:
      image: safespace:latest   # <--- REUSES YOUR LOCAL IMAGE
      options: --gpus all       # <--- GRANTS GPU ACCESS
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Import Verification
        run: |
          python -c "from invisible_core.cloaking import CloakEngine; print('✅ Import OK')"
          python -c "from invisible_core.validation.validator import Validator; print('✅ Validator OK')"
          
      - name: Run Attack Verification
        run: |
          # This script generates the benchmark results
          python invisible_core/tests/benchmark_model.py || echo "Benchmark skipped"
          
      - name: Check Confidence Drop
        run: |
          # Fails if AI confidence > 0.30 (placeholder - adjust based on results.txt)
          if [ -f results.txt ]; then
            python -c "import sys; val=float(open('results.txt').read().strip()); sys.exit(0 if val < 0.3 else 1)"
          else
            echo "results.txt not found, skipping check"
          fi
