name: Heavy CI (Manual)

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run with debug logging'
        required: false
        default: 'false'
      skip_tests:
        description: '⏩ Skip Tests (Only report Skipped Status)?'
        required: false
        default: 'false'
        type: boolean
      skip_teardown:
        description: '⚠️ Skip Teardown (Keep server RUNNING)?'
        required: false
        default: 'false'
        type: boolean

jobs:
  setup-heavy-instance:
    runs-on: linux_cpu_light
    outputs:
      was_skipped: ${{ steps.check.outputs.skipped }}
    steps:
      - id: check
        run: echo "skipped=${{ inputs.skip_tests }}" >> $GITHUB_OUTPUT

      - name: Manual Checkout
        run: |
          echo "⬇️ Cloning repository manually..."
          git clone --depth 1 https://git:${{ github.token }}@gitea.innosol.online/${{ github.repository }}.git .
          
      - name: Wake Up Heavy Server
        if: inputs.skip_tests != true
        env:
          OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
          OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          OVH_PROJECT_ID: ${{ secrets.OVH_PROJECT_ID }}
          OVH_INSTANCE_ID: ${{ secrets.OVH_INSTANCE_ID }}
        run: |
          echo "🚀 Waking up Heavy Instance (via Docker Host Network)..."
          # Use tar pipe to copy scripts into the container (bypasses volume mapping issues)
          tar -cf - scripts/maintenance/ovh_controller.py | docker run --rm --network host -i \
            -w /app \
            -e OVH_APP_KEY -e OVH_APP_SECRET -e OVH_CONSUMER_KEY -e OVH_PROJECT_ID -e OVH_INSTANCE_ID \
            python:3.11-slim \
            bash -c "tar -xf - && pip install ovh && python scripts/maintenance/ovh_controller.py wake"

      - name: Report Status (Pending)
        if: inputs.skip_tests != true && always() && secrets.MIRROR_TOKEN != ''
        env:
           GITHUB_MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          tar -cf - scripts/ci/github_status.py | docker run --rm --network host -i \
            -w /app \
            -e GITHUB_MIRROR_TOKEN \
            python:3.11-slim \
            bash -c "tar -xf - && pip install requests && python scripts/ci/github_status.py \
              --token '$GITHUB_MIRROR_TOKEN' \
              --owner 'innosol-online-OU' \
              --repo 'safesapce' \
              --sha '${{ github.sha }}' \
              --state 'pending' \
              --url '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}' \
              --context 'Gitea/Heavy-Validation' \
              --desc 'Waking up Heavy Server (Unshelving)...'"

      - name: Report Status (Skipped)
        if: inputs.skip_tests == true && secrets.MIRROR_TOKEN != ''
        env:
           GITHUB_MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          tar -cf - scripts/ci/github_status.py | docker run --rm --network host -i \
            -w /app \
            -e GITHUB_MIRROR_TOKEN \
            python:3.11-slim \
            bash -c "tar -xf - && pip install requests && python scripts/ci/github_status.py \
              --token '$GITHUB_MIRROR_TOKEN' \
              --owner 'innosol-online-OU' \
              --repo 'safesapce' \
              --sha '${{ github.sha }}' \
              --state 'success' \
              --url '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}' \
              --context 'Gitea/Heavy-Validation' \
              --desc 'Skipped by Admin (Tests not run).'"

  heavy-validation:
    needs: setup-heavy-instance
    if: needs.setup-heavy-instance.outputs.was_skipped != 'true'
    runs-on: linux_cpu_heavy
    steps:
      - name: Manual Checkout (vRack)
        run: |
          echo "⬇️ Cloning repository via vRack (10.1.0.61)..."
          git clone --depth 1 http://git:${{ github.token }}@10.1.0.61/${{ github.repository }}.git .
          echo "✅ Checkout complete"

      - name: Build Test Environment
        run: |
          echo "🐳 Building CI Image..."
          docker build --no-cache --network=host -t safespace-ci:latest -f Dockerfile.ci .

      - name: Run Verification
        run: |
          echo "🧪 Running Full Pipeline Verification..."
          docker run --rm \
            safespace-ci:latest \
            python tests/verify_full_pipeline.py

      - name: Report Status (Success)
        if: success() && secrets.MIRROR_TOKEN != ''
        env:
           GITHUB_MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          tar -cf - scripts/ci/github_status.py | docker run --rm --network host -i \
            -w /app \
            -e GITHUB_MIRROR_TOKEN \
            python:3.11-slim \
            bash -c "tar -xf - && pip install requests && python scripts/ci/github_status.py \
              --token '$GITHUB_MIRROR_TOKEN' \
              --owner 'innosol-online-OU' \
              --repo 'safesapce' \
              --sha '${{ github.sha }}' \
              --state 'success' \
              --url '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}' \
              --context 'Gitea/Heavy-Validation' \
              --desc 'All Heavy Tests passed!'"

      - name: Report Status (Failure)
        if: failure() && secrets.MIRROR_TOKEN != ''
        env:
           GITHUB_MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          tar -cf - scripts/ci/github_status.py | docker run --rm --network host -i \
            -w /app \
            -e GITHUB_MIRROR_TOKEN \
            python:3.11-slim \
            bash -c "tar -xf - && pip install requests && python scripts/ci/github_status.py \
              --token '$GITHUB_MIRROR_TOKEN' \
              --owner 'innosol-online-OU' \
              --repo 'safesapce' \
              --sha '${{ github.sha }}' \
              --state 'failure' \
              --url '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}' \
              --context 'Gitea/Heavy-Validation' \
              --desc 'Heavy Verification Failed!'"

  teardown-heavy-instance:
    needs: [heavy-validation, setup-heavy-instance]
    if: always() && inputs.skip_teardown != true && needs.setup-heavy-instance.outputs.was_skipped != 'true'
    runs-on: linux_cpu_light
    steps:
      - name: Manual Checkout
        run: |
          echo "⬇️ Cloning repository manually..."
          git clone --depth 1 https://git:${{ github.token }}@gitea.innosol.online/${{ github.repository }}.git .

      - name: Sleep Heavy Server
        env:
          OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
          OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          OVH_PROJECT_ID: ${{ secrets.OVH_PROJECT_ID }}
          OVH_INSTANCE_ID: ${{ secrets.OVH_INSTANCE_ID }}
        run: |
          echo "😴 Suspending Heavy Instance..."
          tar -cf - scripts/maintenance/ovh_controller.py | docker run --rm --network host -i \
            -w /app \
            -e OVH_APP_KEY -e OVH_APP_SECRET -e OVH_CONSUMER_KEY -e OVH_PROJECT_ID -e OVH_INSTANCE_ID \
            python:3.11-slim \
            bash -c "tar -xf - && pip install ovh && python scripts/maintenance/ovh_controller.py sleep"
