name: "Tiered AI Pipeline"

on:
  push:
    branches: [main, dev]
    # Trigger 5: Debug Shell

jobs:
  fast-feedback:
    if: github.event_name == 'push'
    runs-on: linux_cpu_light
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Shell
        run: echo "✅ Hello World from Ubuntu Runner"

      - name: Debug Environment
        run: |
          whoami
          pwd
          ls -la
