name: "Tiered AI Pipeline"

on:
  push:
    branches: [main, dev]
    # Trigger 8: vRack Clone Fix

jobs:
  fast-feedback:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Manual Checkout
        run: |
          echo "⬇️ Cloning repository manually (Public)..."
          git clone --depth 1 https://git:${{ github.token }}@gitea.innosol.online/${{ github.repository }}.git .
          echo "✅ Checkout complete"

      - name: Report Status (Pending)
        if: always() && secrets.GITHUB_MIRROR_TOKEN != ''
        run: |
          python scripts/ci/github_status.py \
            --token "${{ secrets.GITHUB_MIRROR_TOKEN }}" \
            --owner "innosol-online-OU" \
            --repo "safe-space" \
            --sha "${{ github.sha }}" \
            --state "pending" \
            --url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}" \
            --context "Gitea/Fast-Feedback" \
            --desc "Running Lint & Security Checks..."

      - name: Security Scan
        run: |
          echo "🔒 Scanning for exposed secrets..."
          if grep -rE "(RUNNER_TOKEN|API_KEY|SECRET_KEY|PASSWORD|PRIVATE_KEY)=" --include="*.py" --include="*.yml" --include="*.yaml" . 2>/dev/null | grep -v ".env.example" | grep -v ".gitignore"; then
            echo "❌ SECURITY VIOLATION: Secrets found!"
            exit 1
          fi
          echo "✅ No secrets detected"
          
      - name: Verify .env Not Tracked
        run: |
          if git ls-files --error-unmatch .env 2>/dev/null; then
            echo "❌ SECURITY VIOLATION: .env is tracked!"
            exit 1
          fi
          echo "✅ .env is NOT tracked"
          
      - name: Lint with Ruff
        uses: docker://ghcr.io/astral-sh/ruff:latest
        with:
          args: check invisible_core/ app_interface/ --ignore E501,E402
          
      - name: Check Import Structure
        run: |
          if grep -rn "from src\." --include="*.py" invisible_core/ app_interface/; then
            echo "❌ Found old 'from src.' imports!"
            exit 1
          fi
          echo "✅ All imports use new structure"

      - name: Report Status (Success)
        if: success() && secrets.GITHUB_MIRROR_TOKEN != ''
        run: |
          python scripts/ci/github_status.py \
            --token "${{ secrets.GITHUB_MIRROR_TOKEN }}" \
            --owner "innosol-online-OU" \
            --repo "safe-space" \
            --sha "${{ github.sha }}" \
            --state "success" \
            --url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}" \
            --context "Gitea/Fast-Feedback" \
            --desc "All checks passed!"

      - name: Report Status (Failure)
        if: failure() && secrets.GITHUB_MIRROR_TOKEN != ''
        run: |
          python scripts/ci/github_status.py \
            --token "${{ secrets.GITHUB_MIRROR_TOKEN }}" \
            --owner "innosol-online-OU" \
            --repo "safe-space" \
            --sha "${{ github.sha }}" \
            --state "failure" \
            --url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }}" \
            --context "Gitea/Fast-Feedback" \
            --desc "Checks failed. Click for logs."


  heavy-validation:
    needs: fast-feedback
    if: success()
    runs-on: linux_cpu_heavy
    steps:
      - name: Manual Checkout (vRack)
        run: |
          echo "⬇️ Cloning repository via vRack (10.1.0.61)..."
          # Use internal IP to connect from Heavy Server to Light Server via Private Network
          git clone --depth 1 http://git:${{ github.token }}@10.1.0.61/${{ github.repository }}.git .
          echo "✅ Checkout complete"

      - name: Build Test Environment
        run: |
          echo "🐳 Building CI Image..."
          docker build --no-cache --network=host -t safespace-ci:latest -f Dockerfile.ci .

      - name: Run Verification
        run: |
          echo "🧪 Running Full Pipeline Verification..."
          docker run --rm \
            safespace-ci:latest \
            python tests/verify_full_pipeline.py
